# -*- coding: utf-8 -*-
"""Copy of Copy of LeanIn_NLP_Parsing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1UluXsEGW6_2vezKR4hRUiLqvZVTsD_
"""

import re
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import string

from nltk.corpus import stopwords
import nltk
import numba
from numba import jit

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

!unzip english_dataset.zip
!rm -rf english_dataset.zip

"""# Converting to lower case and upper case """

import csv
data = pd.read_csv('english_dataset/english_dataset.tsv', sep='\t')
for row in data:
  data[row]=data[row].str.lower()
data.head(10)

for row in data:
  data[row]=data[row].str.upper()
data.head()

"""# Removing numbers"""

import re
for row in data:
  data[row]=data[row].str.replace('\d+','')
data.head()

"""# Removing punctuations"""

for row in data:
 data[row]=data[row].str.replace('[^\w\s]','')
data.head()

"""# Removing stopwords"""

from nltk.corpus import stopwords
stop =stopwords.words('english')
#data=pd.DataFrame(data)
for row in data:
 data[row]=data[row].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
data.head()

"""#Removing white space"""

for row in data:
 data[row]=data[row].str.replace(' ','')
data.head()